### ISSUE TITLE
Fails to register public token

### ISSUE THREAD

**Issue by ceyo14** [thrnz/docker-wireguard-pia#10]
The following is what I get when starting the container... I have deleted everything and reinstalled it and still get the same issue.

FYI this is on UNRAID and it was working great until a week or 2 ago. What can I do?

`Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: ca_toronto, cn: toronto423, ip: 154.3.42.48
WG key registration failed

Mon Nov 2 18:27:41 UTC 2020: Failed to generate WireGuard config

Mon Nov 2 18:27:41 UTC 2020: Fatal error
`

**Comment by thrnz** [comment]
It looks like curl was suppressing any error messages so apart from the request returning an empty response its hard to see what was going wrong. I've updated the script so any curl errors should now get shown. It might give more of a clue as to why its failing.

**Comment by ceyo14** [comment]
That helped a ton, figured out it was the Threat Prevention Module in Untangle that was blocking it, it is reporting the Client Reputation of the IP as Suspicious... and I recently made a change to also block suspicious not just high-risk....

Sorry for the trouble but the Curl logs did help, good to have them.
