### ISSUE TITLE
Fails.ForbiddenQbittorrent port updated successfully (41749)...

### ISSUE THREAD

**Issue by zackblock** [thrnz/docker-wireguard-pia#101]
Greetings,

I've got docker-wireguard-pia mostly working, except the forwarded port is not getting passed along to qBittorrent.  Instead, this bizarre "Fails.Forbidden" error pops up in the logs, in between running the ports.sh script, and saying it was successful (it wasn't).

Mon Jan 22 21:43:40 UTC 2024: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.14.228.203 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
interface: wg0
  public key: xyz
  private key: (hidden)
  listening port: 46258
  fwmark: 0xca6c
peer: xyz
  endpoint: xxx.xxx.xxx.xxx:1234
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 148 B sent
  persistent keepalive: every 25 seconds
Mon Jan 22 21:43:40 UTC 2024: WireGuard successfully started
Mon Jan 22 21:43:40 UTC 2024: Allowing network access to 172.27.0.2/16 on eth0
Mon Jan 22 21:43:40 UTC 2024: Firewall enabled: Blocking non-WireGuard traffic
Mon Jan 22 21:43:40 UTC 2024: Allowing network access to 192.168.1.0/24 on eth0
Mon Jan 22 21:43:40 UTC 2024: Adding route to 192.168.1.0/24
Mon Jan 22 21:43:40 UTC 2024: Starting port forward script
Mon Jan 22 21:43:40 UTC 2024: Verifying API requests. CN: ontario410
Mon Jan 22 21:43:40 UTC 2024: Getting PF token
Mon Jan 22 21:43:40 UTC 2024: Reusing previous PF token
Mon Jan 22 21:43:45 UTC 2024: Obtained PF token. Expires at 2024-03-25T04:32:17.936302649Z
Mon Jan 22 21:43:45 UTC 2024: Server accepted PF bind
Mon Jan 22 21:43:45 UTC 2024: Forwarding on port 41749
Mon Jan 22 21:43:45 UTC 2024: Rebind interval: 900 seconds
Mon Jan 22 21:43:45 UTC 2024: Port dumped to /pia-shared/port.dat
Mon Jan 22 21:43:45 UTC 2024: This script should remain running to keep the forwarded port alive
Mon Jan 22 21:43:45 UTC 2024: Press Ctrl+C to exit
Mon Jan 22 21:43:45 UTC 2024: Running /scripts/pf_success.sh
Mon Jan 22 21:43:45 UTC 2024: Allowing incoming traffic on port 41749
Mon Jan 22 21:43:45 UTC 2024: Running user-defined command: /pia-shared/ports.sh
Setting qBittorrent port settings (41749)...
Fails.ForbiddenQbittorrent port updated successfully (41749)...

If I run bash ports.sh from the directory, I get the same error.

This did work briefly.  Sabnzbd was already using port 8080, so I tried getting docker-wireguard-pia to use 8282 and changed the ports in the docker compose as well as the ports.sh.  It would not pass along the port to qBittorrent.  I decided to give up and move Sabnzbd to 8282 and then set the docker-wireguard-pia ports back to their default 8080 and low and behold it started working.  But it was short-lived.  I've stopped/started the stack a bunch of times, and I can't get it to pass the port.

Anyone have any ideas what the issue might be?

**Comment by zackblock** [comment]
> Whats inside the custom `ports.sh` script? The container scripts themselves don't seem to be throwing any errors.

Sure.. here's my `ports.sh`

```
#!/bin/bash

port="$1"
QBT_USER=admin
QBT_PASS=mypassword
QBT_PORT=8080

echo "Setting qBittorrent port settings ($port)..."
# Very basic retry logic so we don't fail if qBittorrent isn't running yet
 while ! curl --silent --retry 10 --retry-delay 15 --max-time 10 \
  --data "username=${QBT_USER}&password=${QBT_PASS}" \
  --cookie-jar /tmp/qb-cookies.txt \
  http://localhost:${QBT_PORT}/api/v2/auth/login
  do
    sleep 10
  done

curl --silent --retry 10 --retry-delay 15 --max-time 10 \
  --data 'json={"listen_port": "'"$port"'"}' \
  --cookie /tmp/qb-cookies.txt \
  http://localhost:${QBT_PORT}/api/v2/app/setPreferences

echo "Qbittorrent port updated successfully ($port)..."
```

**Comment by thrnz** [comment]
That script seems to work fine here alongside the `linuxserver/qbittorrent` container with everything set to default:

```
./port.sh 12345
Setting qBittorrent port settings (12345)...
Ok.Qbittorrent port updated successfully (12345)...
```

However, with a wrong username or password it seems to throw that error:

```
./port.sh 12345
Setting qBittorrent port settings (12345)...
Fails.ForbiddenQbittorrent port updated successfully (12345)...
```

It might be worth manually running the following to see whats going wrong. Assuming the user/pass are correct, it looks like it can also fail if there were too many failed login attempts.

`curl -i --header 'Referer: http://localhost:8080' --data 'username=admin&password=somepassword' http://localhost:8080/api/v2/auth/login`


https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#login

**Comment by zackblock** [comment]
> However, with a wrong username or password it seems to throw that error:

> It might be worth manually running the following to see whats going wrong. Assuming the user/pass are correct, it looks like it can also fail if there were too many failed login attempts.

Well, I'm now a little physically ill at the amount of time I wasted troubleshooting this today.  My password was correct, but apparently too complex for Web UI to handle.  It had special characters, upper case, lower case, etc.  I just made a temporary one as simple as could be to test with, all lowercase letters, and it began working like magic.  My goodness.

Thanks for getting me pointed in the right direction.  Do you by chance know Web UI's password complexity requirements/limits?

**Comment by thrnz** [comment]
I'm glad you sussed it out.

I'm not sure what the requirements or limits are for their webui itself, but I can see that script struggling with special characters. `curl`'s `--data-encode` option might be helpful there.
