### ISSUE TITLE
Docker secrets?

### ISSUE THREAD

**Issue by nearcatch** [thrnz/docker-wireguard-pia#11]
Any plans to implement [docker secrets](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images) for the username and password? Ideally I could use secrets for the u/p for both PIA and the proxies.

**Comment by thrnz** [comment]
I'm not familiar with using Docker secrets, but I've done what the docs suggest and have added ```USER_FILE``` and ```PASS_FILE``` vars so the user/pass can be read in from a file if needed.

I've briefly tested using ```USER_FILE=/run/secrets/pia-username``` and ```PASS_FILE=/run/secrets/pia-password``` along with corresponding secrets and it seems to be working.

Let me know if theres any wonkiness, or if adding any more vars would be useful.

**Comment by nearcatch** [comment]
Just tested it, worked great.

The only other suggestion I would have for vars is unrelated, but your container allows for local network exceptions in a space-separated environment variable. It's such a small thing, but most of the other containers I've seen do that as a comma-separated variable? If yours used commas too then I could put my local exceptions into my .env file and maintain it there instead of in a couple different places in my compose file.

**Comment by thrnz** [comment]
I could probably just make it replace the commas with spaces so it can accept either. I don't think that would break anything.

**Comment by nearcatch** [comment]
> I could probably just make it replace the commas with spaces so it can accept either. I don't think that would break anything.

Cheers, that would work. I was trying to figure out a command to run to do it myself but I'm still learning shell and docker and stuff.
