### ISSUE TITLE
It was working with docker secrets but not anymore

### ISSUE THREAD

**Issue by carmatana** [thrnz/docker-wireguard-pia#120]
Hello @thrnz. 

I had configured docker secrets for my user and password and the container was running ok.

Something happened that not any more, now I have to declare credentials in environment variables that it is not very safe

 Thanks for the container and the attention

**Comment by thrnz** [comment]
de9455e is the only recent auth related change, and it shouldn't effect reading in credentials from files at all. It just ensures special characters are properly encoded when generating the auth token.

I don't suppose the logs show any clues as to whats going wrong? It still seems to be working here:

```
vpn-1  | Sat Dec  7 20:40:33 UTC 2024: Reading username from /run/secrets/pia_username
vpn-1  | Sat Dec  7 20:40:33 UTC 2024: Reading password from /run/secrets/pia_password
vpn-1  | Sat Dec  7 20:40:33 UTC 2024: Generating auth token
```

Running the container with the `DEBUG=1` env var set might give some more info. It logs commands as they're run, though it will include sensitive information (tokens/keys etc) so shouldn't be shared as-is. It might show where the auth details are being lost or failing to be read in.

**Comment by carmatana** [comment]
It should have been something else

In my logs there was something related to my credentials so I put them as env variables and WG-PIA ran ok

Now, I went back to have theme in docker secrets and everything is running ok again.

sorry for the false alarm

Thanks thrnz,

**Comment by carmatana** [comment]
Close
