### ISSUE TITLE
Add this to ghcr.io registry

### ISSUE THREAD

**Issue by meek2100** [thrnz/docker-wireguard-pia#122]
@thrnz,
Could you publish this docker to the GitHub registry, so I can pull your updates using ghcr.io/thrnz/docker-wireguard-pia?

It kept failing when I tried, so then I reviewed your published packages and noticed nothing had been posted.

You can check yourself here:
https://github.com/thrnz?tab=packages

**Comment by thrnz** [comment]
I've just had a go at adding support for github's container registry in #123 based on the examples in the [docs](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images). 

I've briefly tested it on my Debian machine and also on an arm based host and both seem to be pulling the image and working as expected.

**Comment by meek2100** [comment]
Thank you this is working great for me on a Debian VM.
