### ISSUE TITLE
Option to keep the last IP address

### ISSUE THREAD

**Issue by P8ntBal1551** [thrnz/docker-wireguard-pia#18]
Some trackers complain if your IP address bounces around. Please add in an option to directly connect to a PIA IP address, or to attempt to connect to the previously connected IP address before detecting a new one.

**Comment by thrnz** [comment]
I've added ```PIA_IP```, ```PIA_PORT``` and ```PIA_CN``` which can be set in order to connect to a specific server. For instance:
```
  - PIA_IP=154.3.42.95
  - PIA_CN=toronto425
  - PIA_PORT=1337
```

I figured that manually setting a specific ip/port/cname would be easier to add (and possibly more useful) than remembering the last used server.
