### ISSUE TITLE
Use the new v6 serverlist document

### ISSUE THREAD

**Issue by KWottrich** [thrnz/docker-wireguard-pia#29]
Per the official PIA wireguard script repo, there is a new v6 serverlist published to the master branch on August 2nd:
https://github.com/pia-foss/manual-connections/commit/e7d4806a9eabc89bc5da17c9e0e2af96bbdf526b

I believe it is a drop-in replacement for the v4 list that is currently queried within wg-gen.sh:get_servers().

**Comment by thrnz** [comment]
Cheers for the heads up. It looks like it now gives multiple servers to pick from for each location, but `wg-gen.sh` should already be able to handle that.

**Comment by KWottrich** [comment]
Thanks for the quick turnaround, @thrnz!  Just to double-check, the signature at the bottom of the v6 list can be verified with the same public key as the v4 file, correct?

**Comment by thrnz** [comment]
It seems to still verify alright. The public key remains [unchanged](https://github.com/pia-foss/desktop/blob/5acc5013ad3fca4ddd79743c1255a0b15f2e3e4b/daemon/src/environment.cpp#L31) in their desktop app, which appears to have been using the v6 serverlist since 2.9.0.
