### ISSUE TITLE
Fatal error, cannot start container after image update

### ISSUE THREAD

**Issue by SosthenG** [thrnz/docker-wireguard-pia#31]
Hello,

This worked fine until last image update. Since I updated the image, the container won't start.
I tried removing it, removing the volumes and starting again, same issue. I even tried on a different computer and it's not working either.

At startup the following error appear:
```
[#] iptables-restore -n
iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'raw'

[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
Thu Sep 16 09:05:05 UTC 2021: Fatal error
```

Here is my docker run command:
```
docker run -d \
    --name pia \
    --cap-add=NET_ADMIN \
    --cap-add=SYS_MODULE \
    --device /dev/net/tun \
    --sysctl net.ipv4.conf.all.src_valid_mark=1 \
    --sysctl net.ipv6.conf.default.disable_ipv6=1 \
    --sysctl net.ipv6.conf.all.disable_ipv6=1 \
    --sysctl net.ipv6.conf.lo.disable_ipv6=1 \
    -p 8282:8112 \
    -p 58846:58846 \
    -v /volume1/docker/pia:/pia \
    -v /volume1/docker/pia-port:/pia-shared \
    -e USER=my-username -e PASS='my-password' \
    -e LOC=swiss \
    -e LOCAL_NETWORK=192.168.1.0/24 \
    -e VPNDNS="8.8.8.8, 8.8.4.4" \
    -e PORT_FORWARDING=1 \
    -e PORT_PERSIST=1 \
    -e EXIT_ON_FATAL=1 \
    --restart unless-stopped \
    thrnz/docker-wireguard-pia:latest
```

Something has changed since last version? What should I do to make it work again?
Thanks.

**Comment by thrnz** [comment]
I've built and tagged `thrnz/docker-wireguard-pia:testing` that rolls back the last change. Let me know if that fixes it and I'll try to work out why it might have broke.

**Comment by SosthenG** [comment]
Hello, it's working fine with the testing build.

**Comment by thrnz** [comment]
Thanks for testing that out. I'll roll back and try to rework the change.

**Comment by thrnz** [comment]
I've redone the previous change and there shouldn't be anything there that can potentially break. Could you try out `testing` again to make sure it still works for your setup?

**Comment by SosthenG** [comment]
Testing is working fine after updating the image, thank you for the quick fix!
