### ISSUE TITLE
pf.sh's api-ip seems to be the wrong ip to use when asking for the forward port (wireguard)

### ISSUE THREAD

**Issue by zestysoft** [thrnz/docker-wireguard-pia#34]
Hello!

When the pf.sh script runs, this happens:
```
curl: (7) Failed to connect to vancouver412 port 19999 after 0 ms: Connection refused
Mon Nov  1 06:17:01 UTC 2021: getSignature error

Mon Nov  1 06:17:01 UTC 2021: Fatal error
```

I exec'd into the running container and traced through the code, and it is correctly using traceroute to retrieve the first hop ip address, but that ip address doesn't have port 19999 open, so the connection is refused:

```
curl --get --silent --show-error --retry 5 --retry-delay 15 --max-time 15 --data-urlencode token=<redacted> --cacert /tmp/tmp.bFhmHP --resolve vancouver412:19999:10.33.128.1 https://vancouver412:19999/getSignature
curl: (7) Failed to connect to vancouver412 port 19999 after 0 ms: Connection refused
```

10.33.128.1 also matched what was found in the /etc/wireguard/wg0.conf file:
`#pf api ip: 10.33.128.1`
I was able to get it to work by using the ip address of the peer endpoint found in the /etc/wireguard/wg0.conf file:
```
[Peer]
PublicKey = <redacted>
AllowedIPs = 0.0.0.0/0
Endpoint = 208.78.42.223:1337
```

```
curl --get --silent --show-error --retry 5 --retry-delay 15 --max-time 15 --data-urlencode token=<redacted> --cacert /tmp/tmp.bFhmHP --resolve vancouver412:19999:208.78.42.223 https://vancouver412:19999/getSignature
{
    "status": "OK",
    "payload": "<redacted>",
    "signature": "<redacted>"
}
```

**Comment by thrnz** [comment]
I've had a quick play and am unable to reproduce this. Using either the IP provided by the API or the server's external IP both appear to work as expected.

I vaguely recall issues with the port forward script for a particular setup that was solved by manually telling curl which interface to use. I don't suppose running `/scripts/pf.sh -t /pia/.token -f wg0`, or alternatively adding `--interface wg0` to the `curl` command line fixes it?

```
bash-5.1# /scripts/pf.sh -t /pia/.token
Sat Nov  6 02:19:42 UTC 2021: Using 10.33.128.1 as API endpoint
Sat Nov  6 02:19:42 UTC 2021: Using vancouver412 as cn
Sat Nov  6 02:19:42 UTC 2021: Getting PIA ca cert
Sat Nov  6 02:19:43 UTC 2021: Verifying API requests. CN: vancouver412
Sat Nov  6 02:19:43 UTC 2021: Getting PF token
Sat Nov  6 02:19:45 UTC 2021: Obtained PF token. Expires at 2022-01-07T14:15:02.516302094Z
Sat Nov  6 02:19:45 UTC 2021: Server accepted PF bind
Sat Nov  6 02:19:45 UTC 2021: Forwarding on port 47954
Sat Nov  6 02:19:45 UTC 2021: Rebind interval: 900 seconds
Sat Nov  6 02:19:45 UTC 2021: This script should remain running to keep the forwarded port alive
Sat Nov  6 02:19:45 UTC 2021: Press Ctrl+C to exit
```

```
bash-5.1# /scripts/pf.sh -t /pia/.token -i 208.78.42.223
Sat Nov  6 02:20:28 UTC 2021: Using vancouver412 as cn
Sat Nov  6 02:20:28 UTC 2021: Getting PIA ca cert
Sat Nov  6 02:20:29 UTC 2021: Verifying API requests. CN: vancouver412
Sat Nov  6 02:20:29 UTC 2021: Getting PF token
Sat Nov  6 02:20:30 UTC 2021: Obtained PF token. Expires at 2022-01-07T14:15:48.053742658Z
Sat Nov  6 02:20:30 UTC 2021: Server accepted PF bind
Sat Nov  6 02:20:30 UTC 2021: Forwarding on port 51820
Sat Nov  6 02:20:30 UTC 2021: Rebind interval: 900 seconds
Sat Nov  6 02:20:30 UTC 2021: This script should remain running to keep the forwarded port alive
Sat Nov  6 02:20:30 UTC 2021: Press Ctrl+C to exit
```

**Comment by zestysoft** [comment]
That fixed it.  I probably should have mentioned this is running in a kubernetes pod (containerd), so maybe that might explain the different behavior.

**Comment by zestysoft** [comment]
Ah, I think I know what happened.  Earlier in my troubleshooting a different issue, I had added 10.0.0.0/8 to the list of LOCAK_NETWORK values.  Since the API IP address returned is a 10.x ip address, the traffic didn't go out wg0 by default.

I've removed that 10/8 range from my local network and fine tuned it to the smaller net range that kubernetes uses.

**Comment by thrnz** [comment]
Glad you got it sorted. I'll add a note to the readme in case someone else bumps into the same problem in future.

**Comment by thrnz** [comment]
The port forwarding script now uses wg0 when run. Hopefully that should be enough to be able to use 10.0.0.0/8 as a `LOCAL_NETWORK` if needed and prevent it being an issue in future. The only other conflict that comes to mind would be the default PIA dns servers - 10.0.0.243 10.0.0.242 - though using Google's or Cloudflare's instead is an easy enough fix.
