### ISSUE TITLE
iptables is broken with latest centos update

### ISSUE THREAD

**Issue by P8ntBal1551** [thrnz/docker-wireguard-pia#37]
```
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.7 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

That keeps repeating in the log. it has to do with the version of iptables on the container not being compatible with the iptables of the kernal of the host OS. (In my case CentOS 8, but also Rocky Linux)

I was helping the gluetun maintainer with the same issue here.

https://github.com/qdm12/gluetun/issues/734

**Comment by thrnz** [comment]
If it's just a matter of changing the `/sbin/iptables` symlink to point to `xtables-nft-multi` instead of `xtables-legacy-multi` then it should be easy enough to work around. I wonder if there's a 'correct' way to do that in an Alpine container.

Looks like I've got some reading to do.

**Comment by thrnz** [comment]
I don't suppose [this](https://github.com/thrnz/docker-wireguard-pia/commit/7a2bf00669bc589800dd38b0d3d7ac09f1e96d24) fixes it? You can test it out using ` thrnz/docker-wireguard-pia:testing`, though make sure to add an  `NFTABLES=1` env var first.

**Comment by P8ntBal1551** [comment]
Holy shit, that works beautifully. Thank you for the quick turn around on that.
