### ISSUE TITLE
How can I change the allowedips?

### ISSUE THREAD

**Issue by mfizz1** [thrnz/docker-wireguard-pia#50]
I want the script to change from allowedips= 0.0.0.0/0 to 0.0.0.0/1, 128.0.0.0/1 as it is a known problem on some systems.

As it stands I have an error which I believe can be resolved with this:

```
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
RTNETLINK answers: File exists
[#] resolvconf -d wg0 -f
[#] ip link delete dev wg0
```

**Comment by thrnz** [comment]
You'd have to edit `wg-gen.sh` directly to change the ```AllowedIPs``` value in the generated wg0.conf. I'm not sure what the consequences of this would be, as `wg-quick` behaves [differently ](https://git.zx2c4.com/wireguard-tools/tree/src/wg-quick/linux.bash#n174)if it's not specified as a /0.

You're not the only person to requst modifying `AllowedIPs`, so I could probabaly add it as an env var is people want to set it themselves.

**Comment by mfizz1** [comment]
Yes please, leave it as default and the ability to override using env variables. Unfortunately on cheaper / embedded devices, it does not understand the /0 so we have to replace it with 0.0.0.0/1 and 128.0.0.0/1

**Comment by thrnz** [comment]
I've added an `ALLOWEDIPS` env var to the testing branch. Setting it will override the value of AllowedIPs in the generated wg0.conf. You can either build it yourself or use `thrnz/docker-wireguard-pia:testing` from docker hub. You may find that other things won't work as expected if its changed from the default though, as `wg-quick` behaves differently when it's not a `/0`. You may want to check out #49.
