### ISSUE TITLE
Not able to use the PIA VPN port in rtorrent

### ISSUE THREAD

**Issue by giejay** [thrnz/docker-wireguard-pia#54]
When I try to use the port that has been written to the port.dat file in rtorrent, it fails to boot up: 

Could not open/bind port for listening: Address in use.

rtorrent-config:
network.port_range.set = 35256-35256

Does docker-wireguard-pia do something to claim that port? When I run rtorrent without using the network of this container, it boots up fine.

**Comment by thrnz** [comment]
Apart from dumping the port number to that file, [this](https://github.com/thrnz/docker-wireguard-pia/blob/master/pf_success.sh) is all thats done once the port number is known. Unless you're doing fancy routing stuff, generally the only thing it does is allow incoming tcp/udp traffic on that specific port. The container doesn't do anything else or bind anything to the port itself.

**Comment by giejay** [comment]
My stupid bad... I ran netstat, saw that the port was indeed in use and then realized I still had Deluge running (was comparing torrent clients) and of course, that was already using the port. Stopped deluge and its fixed. Thanks for the feedback!
