### ISSUE TITLE
Problem with authentication parse error

### ISSUE THREAD

**Issue by Ouroboros1337** [thrnz/docker-wireguard-pia#57]
Hello,

I cant seem to get the container running, can you provide help?

Log:
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: swiss, cn: zurich407, ip: 156.146.62.210
Auth failed
Wed Oct 26 11:18:54 UTC 2022: Generating auth token
parse error: Invalid numeric literal at line 1, column 5
Wed Oct 26 11:18:54 UTC 2022: Failed to acquire new auth token
Wed Oct 26 11:18:54 UTC 2022: Fatal error

Docker-compose:

version: '3'
services:
    vpn:
        container_name: vpn
        image: thrnz/docker-wireguard-pia:latest
        volumes:
            # Auth token is stored here
            - /mnt/share/docker-wireguard-pia/pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - /mnt/share/docker-wireguard-pia/shared:/pia-shared
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
            - SYS_MODULE
        # Mounting the tun device may be necessary for userspace implementations
        #devices:
        #  - /dev/net/tun:/dev/net/tun
        environment:
            # The following env vars are required:
            - LOC=swiss
            - "USER=pmysuser111" #i tried it without " and with only the password in " like PASS="Password" too same result
            - "PASS=mypass123"
            # The rest are optional:
            #- LOCAL_NETWORK=192.168.1.0/24
            #- KEEPALIVE=25
            - VPNDNS=1.1.1.1
            - PORT_FORWARDING=1
            #- WG_USERSPACE=1
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

**Comment by thrnz** [comment]
`parse error: Invalid numeric literal at line 1, column 5`

The only way I can reproduce that error is by using an incorrect username or password.

`"USER=pmysuser111"`
I don't suppose that's a rogue 'p' before the username?

Actually, I can see how the readme might be  bit ambiguous there. I should probabaly update that.

**Comment by Ouroboros1337** [comment]
Thank you for your quick response,

I have found the problem. :) 
It seems like the fault lies in the parsing of the password.
I had a auto generated password simmilar to 2itJ%4$kSUgG%Kv9bgY so either $ or % might not get parsed.
I changet my password and now it works.

**Comment by thrnz** [comment]
I've just tidied up `pia-auth.sh` a bit so it behaves more like PIA's own scripts. It was a bit 'hacky' before, and might be able to handle special password characters now too (might be related to #61).
