### ISSUE TITLE
FR: ARM support

### ISSUE THREAD

**Issue by rhinot** [thrnz/docker-wireguard-pia#6]
[Feature request]
Compile an ARM (specifically a armhf) docker image

Thanks for considering.

**Comment by Tdarnell** [comment]
I would also love this feature for raspberry PI installations

**Comment by thrnz** [comment]
I've setup builds for arm32v6 and arm64v8 on Docker Hub, though as my own Pi seems to be MIA I haven't been able to test to see if things work as expected or not.

They're tagged as ```thrnz/docker-wireguard-pia:arm32v6``` and ```thrnz/docker-wireguard-pia:arm64v8```

**Comment by thrnz** [comment]
Since switching to building using Github Actions, `thrnz/docker-wireguard-pia:latest` should work on ARM without needing to use specific tags. Those previously tagged images on Docker Hub are no longer updated.
