### ISSUE TITLE
Token cannot be queries (parse error: Invalid numeric literal at line 1, column 6)

### ISSUE THREAD

**Issue by bernhard-da** [thrnz/docker-wireguard-pia#61]
hi @thrnz first of, thanks a lot for providing and maintaining this image that I am using for a very long time without any issues;

but in the last few days, without changing anything in my docker-compose file, I am experiencing something similar as described in #57 when I do a `docker-compose up`

```
pia-wireguard  | ++ curl --silent --show-error --request POST --max-time 15 --header 'Content-Type: application/json' --data '{"username":"my_correct_username","password":"my_correct_password"}' https://www.privateinternetaccess.com/api/client/v2/token
pia-wireguard  | ++ jq -r .token
pia-wireguard  | parse error: Invalid numeric literal at line 1, column 6
pia-wireguard  | + TOK=
```

The funny thing is that when I just copy the curl-command from the compose-log

```
curl --silent --show-error --request POST --max-time 15 --header 'Content-Type: application/json' --data '{"username":"my_correct_username","password":"my_correct_password"}' https://www.privateinternetaccess.com/api/client/v2/token
```

directly into a shell, I do get a valid response (and a token)

```
{"token":"some_token"}
```

Therefore I know that my User/Pw are correct and something else is going on. Is there anything I could try to fix this issue? Thx a lot!

**Comment by bernhard-da** [comment]
@thrnz sorry for the noise; after some time, it works now as expected again; I guess this was a glitch at pia;

**Comment by thrnz** [comment]
I've just tidied up `pia-auth.sh` a bit so it behaves more like PIA's own scripts. It was a bit 'hacky' before and was failing when special characters were in the username/password. I'm not sure if that was related to this one or not, but it hopefully solves #57.
