### ISSUE TITLE
iptables-restore v1.8.8 (legacy): iptables-restore: unable to initialize table 'raw'

### ISSUE THREAD

**Issue by chaoskcw** [thrnz/docker-wireguard-pia#65]
Hi

I seem to be getting the above error with up tables and table "raw". I took latest and run it with high priv. 

This is on a Synology DS415+. Celeron I think. Any thoughts ? 

<img width="948" alt="Screenshot_03_03_2023__16_28" src="https://user-images.githubusercontent.com/1980464/222775198-9f6ab2c7-6725-415c-a045-2d4493abb17d.png">

**Comment by thrnz** [comment]
This might be the same issue as #49 and #39. Unfortunately I'm not sure how best to work around it.

The container uses `wg-quick` to handle setting up the Wireguard interface. From what I understand, `wg-quick` throws that error occurs when a particular kernel module (iptable_raw) isn't available.

**Comment by chaoskcw** [comment]
Ok thx
