### ISSUE TITLE
PIA server endpoint is incorrect, cannot get reponse data

### ISSUE THREAD

**Issue by jerryjudy** [thrnz/docker-wireguard-pia#7]
https://serverlist.piaservers.net/vpninfo/servers/new seems to be incorrect. I updated it to https://serverlist.piaservers.net/vpninfo/servers/v4 and that seemed to do the trick.

**Comment by thrnz** [comment]
Thanks for that. It looks like it was changed to 'v4' in v2.3.0 of their desktop app. Their standalone scripts also seem to use 'v4', so hopefully they don't plan on changing it again the near future.

**Comment by jerryjudy** [comment]
You’re very welcome! Once that change was made and I made my own docker image out of your stuff it worked great! I really appreciate your work. Much faster than the openvpn versions I was trying to use before.
