### ISSUE TITLE
Ping Operation not permitted, Failed to generate Wireguard config, Fatal Error

### ISSUE THREAD

**Issue by SimpleMachine247** [thrnz/docker-wireguard-pia#70]
I cant seem to get this working. Every time I try to get this up and running I run into an issue where I have a connection timeout in the log which causes the failure, and the health check apparently is not allowed to ping. I've been scouring the internet for an answer to this but just can't find anything.

Portainer log (relevant lines):

> /scripts/wg-gen.sh -l us_seattle -t /pia/.token -o /etc/wireguard/wg0.conf -k /RegionsListPubKey.pem -d 192.168.1.250 -m ''
Fetching next-gen PIA server list
Verified OK
Verified server list
curl: (28) Connection timed out after 120001 milliseconds
curl: (28) Connection timed out after 120001 milliseconds
curl: (28) Connection timed out after 120001 milliseconds
curl: (28) Connection timed out after 120000 milliseconds
curl: (28) Connection timed out after 120001 milliseconds
curl: (28) Connection timed out after 120001 milliseconds
Failed to download PIA ca cert
result=1
'[' 1 -eq 2 ']'
'[' 1 -eq 3 ']'
'[' 1 -ne 0 ']'
date
echo 'Thu Apr 13 04:19:17 UTC 2023: Failed to generate WireGuard config'
fatal_error
Thu Apr 13 04:19:17 UTC 2023: Failed to generate WireGuard config
date
echo 'Thu Apr 13 04:19:17 UTC 2023: Fatal error'
Thu Apr 13 04:19:17 UTC 2023: Fatal error
'[' 0 -eq 1 ']'
wait 263
sleep infinity

Docker Compose:

> VPN-proxy:
    container_name: VPN-proxy
    image: thrnz/docker-wireguard-pia
    restart: always
    networks: 
      - web-proxy
    cap_add:
      - NET_ADMIN
      #- SYS_MODULE might not be needed with a 5.6+ kernel?
      #- SYS_MODULE
      # Mounting the tun device may be necessary for userspace implementations
      #devices:
      #- /dev/net/tun:/dev/net/tun
    privileged: true
    sysctls:
      # wg-quick fails to set this without --privileged, so set it here instead if needed
      - net.ipv4.conf.all.src_valid_mark=1
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s # While testing container, change to 10s. To prevent constant logfile activity, change to a few minutes
      timeout: 10s
      start_period: 10s
      retries: 3
    environment:
      LOCAL_NETWORK: 192.168.1.0/24,10.0.0.0/24
      LOC: us_seattle
      USER: $VPN_USER_PIA
      PASS: $VPN_PW_PIA
      #KEEPALIVE: 25
      VPNDNS: 192.168.1.250
      PORT_FORWARDING: 0
      PORT_PERSIST: 0
      PORT_SCRIPT: /pia-shared/updateport-qb.sh
      DEBUG: 1
      #WG_USERSPACE: 1
    volumes:
      # Auth token is stored here
      - $DOCKERDIR/vpn-proxy/pia:/pia
      # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
      - $DOCKERDIR/vpn-proxy/pia-shared:/pia-shared
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    ports:
      - 9090:8080 #Qbittorrent webUI
    labels:
      org.hotio.pullio.update: true
      caddy: http://downloads.home
      caddy.reverse_proxy: "{{upstreams 8080}}"
      plugsy.name: VPN-Proxy
      plugsy.parents: Downloads

Health Check Output:

> PING www.google.com (142.251.33.68): 56 data bytes ping: sendto: Operation not permitted

**Comment by thrnz** [comment]
From the logs it looks like  `wg-gen.sh` appears to be downloading the server list alright, but then failing to download the PIA ca cert and dying as a result.

It might be worth temporarily trying with `FIREWALL=0` just to rule out anything being blocked by the container itself, although the fact that the server list seems to be downloading without issue then I guess this would be unlikely.

It might also be worth checking that the PIA ca cert downloads correctly from outside the container just to rule out a network issue elsewhere. It's downloaded from here: https://raw.githubusercontent.com/pia-foss/desktop/master/daemon/res/ca/rsa_4096.crt

I imagine the healthcheck is then failing as non-vpn traffic is blocked by default (with a few temporary exemptions for setup), and the container is dying before being able to bring up the wireguard interface.

I should probably update `wg-gen.sh` to use the included copy of the cert rather than needing to redownload it.

**Comment by SimpleMachine247** [comment]
Thanks! I will go through this and let you know what I find.

**Comment by thrnz** [comment]
I've tweaked the config generator a bit so it can use the existing cert rather than redownloading it. I'm not sure if that'll help here though - it'll probably just move he error elsewhere.

**Comment by SimpleMachine247** [comment]
So I started to rebuild everything from scratch a few days ago while waiting for an answer (trying to figure it out myself) and now it's running perfectly. After some thought I think I may know what was causing the issue, just not really why. 

I had the entire server computer connected to wireguard VPN outside of docker previously. This time I skipped that step, and now it's working. I'm going to assume it had something to do with already having a wireguard config set up and running on the computer. If you have any insight here I'd love to hear it. But I think we can close this.

**Comment by thrnz** [comment]
I've only ever run the container on a basic Debian install, so I'm not sure if running docker itself behind a vpn could've been breaking something. Maybe it was causing that request to `raw.githubusercontent.com` to fail somehow, although I'd assume other containers might have also had networking issues if that was the case.

Glad it's working now though.
