### ISSUE TITLE
Network interface not named eth*

### ISSUE THREAD

**Issue by lehmanju** [thrnz/docker-wireguard-pia#71]
I am trying to run this container with other containers inside a rootless pod using podman. However, because the network interface is not named `eth*` but `tap*` , many `iptables` commands fail.

Maybe there is a way to generalize over interface names, since every network driver uses different names?

For my setup I have adapted the script to work with `tap*` (https://github.com/lehmanju/docker-wireguard-pia/commit/f953e387b23417c174ca252329ce346ec2253918)

**Comment by thrnz** [comment]
Would something like #73 work?

The previous assumption was that all attached docker related networks would be picked up with `eth*`. It now instead loops over all interfaces, skipping over loopback and wireguard. In most cases I think this would functionally be the same - there's generally only the `lo`, `wg0` and `ethxx` interfaces present - but it should now pick up and allow input/output to anything else as well regardless of name.

The hardcoded interface name is dropped altogether for the `LOCAL_NETWORK` stuff as it's probabaly not needed.
