### ISSUE TITLE
Have multiple LOC values in case one is down

### ISSUE THREAD

**Issue by carmatana** [thrnz/docker-wireguard-pia#76]
First of all, GREAT image ! My synology does nos support WG but this container runs without any problem !

I wonder if it is possible to have multiple LOCs (or endpoints) in the ENV variable, for example:

LOC=swiss,ca_ontario,us_california,de_berlin

Just in case one location is not responding.

I have seen other images doing this but with oven, I guess with WG is possible too

Thanks again for this great image

**Comment by thrnz** [comment]
Glad to hear that the containers running well for you.

Would something like #77 solve this?

The idea is that if a location id no longer exists or isn't responding when the container starts, it'll move on and try the next. It should work with both a space or comma separated list of ids.

It still won't be able to recover if the endpoint goes down later on, but would allow fallback if the initial config generation fails.

Recovering once the wireguard interface goes up would be a bit more awkward. I think changing the wireguard endpoint should be possible without bringing the interface down, but would be awkward having to work around existing routing and the firewall when re-generating the config, along with stuff potentially running in other containers sharing the connection. To keep things simple the container leaves most of that fun stuff up to `wg-quick`.

**Comment by thrnz** [comment]
If you want to test it out and are using docker-compose, replacing `image: thrnz/docker-wireguard-pia` with `build: https://github.com/thrnz/docker-wireguard-pia.git#multi-loc` should do the trick, otherwise I can push and tag it on docker hub if needed.

**Comment by carmatana** [comment]
> Recovering once the wireguard interface goes up would be a bit more awkward. 

I was not expecting or meaning this, only the part when the container is started




> If you want to test it out and are using docker-compose, replacing `image: thrnz/docker-wireguard-pia` with `build: https://github.com/thrnz/docker-wireguard-pia.git#multi-loc` should do the trick, otherwise I can push and tag it on docker hub if needed.

Not sure what do you mean ? Building an image using the Dockerfile and other files in that link. I have never done that except but I can try.

However, if it is something that you have plans to release soon I can wait too.

Thanks for the attention !

**Comment by carmatana** [comment]
> If you want to test it out and are using docker-compose, replacing `image: thrnz/docker-wireguard-pia` with `build: https://github.com/thrnz/docker-wireguard-pia.git#multi-loc` should do the trick, otherwise I can push and tag it on docker hub if needed.

My synology does not have git, so I got an error when using `build: https://github.com/thrnz/docker-wireguard-pia.git#multi-loc` in my docker-compose yml

so I went to that page and downloaded the zip file but it seems that when I did that I was getting the "normal" version and not the "multi-loc" one. when running the container I got a fatal error for using multiple locations.

then I used `git clone https://github.com/thrnz/docker-wireguard-pia.git#multi-loc` in MacOS but I got this error

`fatal: unable to update url base from redirection:
  asked for: https://github.com/thrnz/docker-wireguard-pia.git#multi-loc/info/refs?service=git-upload-pack
   redirect: https://github.com/thrnz/docker-wireguard-pia`

and nothing was downloaded.
   
So I could not get the multi-loc version.

**Comment by thrnz** [comment]
I've tested the changes using location ids that are not in the server list and it seems to work, but it should handle unresponsive servers in the same way, and try the next one given instead.

I'll probably merge the changes as-is as it should hopefully be doing whats needed. The updated container will be available shortly after.

**Comment by carmatana** [comment]
Thanks !
