### ISSUE TITLE
Kill switch support?

### ISSUE THREAD

**Issue by CraniumFarmer** [thrnz/docker-wireguard-pia#85]
Forgive my lack of understanding, but is a kill switch used or should it be used? I'm looking to understand if traffic can leak through if the VPN goes down or if the VPN experiences connectivity issues.

**Comment by thrnz** [comment]
The container uses `wg-quick` to handle most of the network stuff. It overrides the container's default gateway, meaning that all traffic then gets routed through the encrypted tunnel. The only exclusions are for any manually defined `LOCAL_NETOWRK`s and attached docker bridge networks.

My understanding is that Wireguard doesn't go down in the same way that OpenVPN might. If the connection dies and the remote endpoint stops responding, then the routing rules still remain, and it shouldn't be possible for anything to leak out unencrypted. The container would just lose any functional network connectivity.

As a back up though, in case something does go wrong, the container also adds firewall rules where all network traffic is dropped by default, and only encrypted/tunnelled traffic is explicitly allowed (this can be disabled using `FIREWALL=0` if desired). While a kill-switch might only kick in once the connection dies, these firewall rules should prevent unexpected leaks at any time. I'm not sure it's strictly needed as I think `wg-quick` has everything covered already via routing, but there doesn't seem to be a downside to including it anyway by default just as a fallback.

Here's a bit more reading if you're interested:
https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
https://www.wireguard.com/netns/#routing-all-your-traffic

**Comment by CraniumFarmer** [comment]
I appreciate the detailed response and added context! This helps a lot.
