### ISSUE TITLE
/scripts/pf_success.sh: line 25: /pia-shared/updateport-qb.sh: Permission denied

### ISSUE THREAD

**Issue by BastionNtB** [thrnz/docker-wireguard-pia#88]
Hello there again.

Got everything squared away except for one little tiny detail. I'm using a script to push the port number from the VPN to qbittorrent.

I've got the path to the script defined in the `PORT_SCRIPT='/pia-shared/updateport-qb.sh'` under the environment.

However, as the error suggests, it says it permission is denied.

From both the container and from the volume it's mapped from the file is 775.

`-rwxrwxr-x    1 root     root           699 Dec 19 19:22 updateport-qb.sh`

Any tips or ideas what I should look into next?

**Comment by thrnz** [comment]
Nothing immediately comes to mind.

Running the container with the `DEBUG=1` env var set might be something to try, as it might give some clues as to which command is failing.

Does the custom script run as expected when manually run inside the container?

**Comment by BastionNtB** [comment]
It started just working on it own, I have no idea why.

Only thing I did was restarted it once again (for like the 10th time btw) and it just worked...
