### ISSUE TITLE
wireguard-pia dies during startup if serverlist.piaservers.net is not available

### ISSUE THREAD

**Issue by demigh0d** [thrnz/docker-wireguard-pia#89]
serverlist.piaserves.net is down. wireguard-pia retries for a while, then gives up.

```
Fetching next-gen PIA server list
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
Fetching next-gen PIA server list
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
Error reading signature file /tmp/tmp.LnahiF
Failed to verify server list
Thu Dec 21 04:00:51 UTC 2023: Failed to generate WireGuard config
Thu Dec 21 04:00:51 UTC 2023: Fatal error
```

It hasn't gotten to the point where the healthcheck is started so the container stays down until manually restarted.

Going to the url in a web browser results in a nginx 404. isitup.org confirms that it is not reachable.

**Comment by thrnz** [comment]
I think its normal for https://serverlist.piaservers.net to throw a 404 - I don't think its a full website as such. The full server list url that the container needs to pull is https://serverlist.piaservers.net/vpninfo/servers/v6 - It might be worth checking that in a browser or on the Docker host just to make sure its working.

I guess that error suggests there might be a name resolution issue somewhere. Running `nslookup serverlist.piaservers.net` inside the container might be somewhere to start.

An alternative would be to manually set the `PIA_IP`, `PIA_CN` and `PIA_PORT` env vars to bypass needing to download the server list at all. I think the port is always 1337 for Wireguard, and the ip and cn would need to be manually chosen from that server list url. Something like this should work without needing any dns lookups: `PIA_IP=102.129.145.193`, `PIA_CN=losangeles431`, `PIA_PORT=1337`

**Comment by demigh0d** [comment]
Not sure what's going on....

I have it and 2 other apps in the one stack. It won't resolved from the other 2 containers either but they are set with network_mode: "service:vpn"  

I also tried from apps in 2 other stacks, on the same docker server, and they had no trouble resolving it.

**Comment by demigh0d** [comment]
I removed network_mode: "service:vpn" from one of the other containers.

I was then able to connect to it and successfully ping serverlist.piaserves.net. wireguard-pia still doesn't come up.

I've already tried deleting the container, deleting the image and recreating it.

**Comment by BlomsD** [comment]
I have the same problem and it kills the entire VPN process. This latest update has completely broken it.

Note removing network_mode: "service:vpn" means that container isn't running through the VPN anymore

**Comment by thrnz** [comment]
> This latest update has completely broken it.

If it was working previously, then it could be related to #90. Alpine made a change in their latest release, which could cause issues on some setups. It would have been introduced on the docker hub build when the container was rebuilt on the 19th.

I don't suppose there's any iptables related errors showing up in the logs at all?
