### ISSUE TITLE
Iptables not working on QNAP after update?

### ISSUE THREAD

**Issue by roydufek** [thrnz/docker-wireguard-pia#90]
Keep getting the following errors in logs:

Warning: Extension udp revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument

I believe that it 1.8.10 is too new? Can't update or load nf_tables on module in the QNAP kernel. Was working beautifully for a year, just broke within the last week. Tried everything I can. A bit new to the linux and docker back end but NFTABLES=0/1 doesn't fix either. Doesn't seem to be using Legacy anymore though...

Thanks for any help! Apologies if this sounds naive-

**Comment by thrnz** [comment]
It looks like Alpine 3.19 was released a couple of weeks ago, and according to the [release notes](https://alpinelinux.org/posts/Alpine-3.19.0-released.html) `iptables-nft` is now default. I guess I'll need to add something that does the opposite of what the `NFTABLES` env var did so the old behavior can still be used when needed.

**Comment by thrnz** [comment]
I've had a go at fixing this in #91. I've also built and tagged it as `testing` so it's easier to test out. You'll need to use `image: thrnz/docker-wireguard-pia:testing` and set the `NFTABLES=0` env var to give it try.

**Comment by roydufek** [comment]
I used :testing and NFTABLES=0 and that worked! Thank you- shoot me a dm, I'd love to send some $ your way for your troubles. That was super fast and during the holidays- :) Super appreciate it!

**Comment by thrnz** [comment]
Excellent. I want to try to see if I can get it to automatically detect when it needs to fall back to `iptables-legacy` without needing an env var set before I merge the fix so it doesn't catch out anyone else in future. Could you try updating and running the testing tagged build again, but without the `NFTABLES` env var set to see if it still works?

Thanks for the donation offer, I really appreciate it. I don't have anything set up for that kind of thing though, but I'm sure a local animal shelter could make much better use of any spare cash than I could!

**Comment by roydufek** [comment]
You're too kind- thanks again, truly...

I did redeploy without the env var. All is good!

![image](https://github.com/thrnz/docker-wireguard-pia/assets/131901961/1dce8eaa-6219-4737-83fd-4b27ece5ecb8)

**Comment by roydufek** [comment]
Oh I guess looking at the logs I see this:

![image](https://github.com/thrnz/docker-wireguard-pia/assets/131901961/31bcd6f6-8c67-4a6a-bb9b-d5370ad8c852)

Not sure if it affects my needs though...

**Comment by thrnz** [comment]
I vaguely recall a missing kernel module causing that 'raw' table error. I'm unsure if it''ll be related to the change in defaults in Alpine 3.19 -  after this change it should go back to functioning how it was before.

**Comment by carmatana** [comment]
it seems that this error came back

I started to have in the logs the following error:

Warning: Extension addrtype revision 0 not supported, missing kernel module?
Warning: Extension comment revision 0 not supported, missing kernel module?
Warning: Extension udp revision 0 not supported, missing kernel module?
iptables v1.8.11 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables v1.8.11 (nf_tables): Could not fetch rule set generation id: Invalid argument
Warning: Extension tcp revision 0 not supported, missing kernel module?
iptables v1.8.11 (nf_tables): Could not fetch rule set generation id: Invalid argument
iptables v1.8.11 (nf_tables): Could not fetch rule set generation id: Invalid argument
Tue Feb 18 04:40:31 UTC 2025: Bringing up WireGuard interface wg0
Tue Feb 18 04:40:33 UTC 2025: Firewall enabled: Blocking non-WireGuard traffic
Tue Feb 18 04:40:33 UTC 2025: Allowing network access to 192.168.1.0/24 on eth0
Device "syno_ovs_bonds" does not exist.
iptables v1.8.11 (nf_tables): Could not fetch rule set generation id: Invalid argument
