### ISSUE TITLE
QBT WebUI not working on newest docker - Mac

### ISSUE THREAD

**Issue by mrchrisster** [thrnz/docker-wireguard-pia#98]
Hey, 

I just updated Docker (Jan 15, 2024) and I can't access webui for QBT anymore. In the logs I found
`[QtSingleCoreApplication: listen on local socket failed`
I reverted to Docker 4.2.1 as a test and everything works as expected again

**Comment by BastionNtB** [comment]
Not an owner or contributor to this git, but this is for the PIA vpn docker. This really doesn't have anything to do with qbittorrent. You might want to check with the maintainer of your qbittorrent container image.

**Comment by mrchrisster** [comment]
I'm aware it's OT but I think a lot of people run this in combination with QBT. I also didn't see any info on the GitHub page for QBT so maybe this just affects the combination of pia w. QBT

**Comment by mrchrisster** [comment]
I was able to fix it by assigning the port to my network. - `192.168.10.190:9090:9090`
I still get `bad address` on almost every torrent

**Comment by thrnz** [comment]
Is qBittorrent bound to the `wg0` interface? IIRC by default it binds to everything, which might cause issues with peer/tracker traffic when using vpns.

**Comment by mrchrisster** [comment]
Yes, bound to wg0. Just actually trying to fix this ATM. Just started a new torrent and it errors out right away. It's strange though, only some do.. other complete no problem. The log always shows "bad address"

**Comment by mrchrisster** [comment]
I'm carefully optimistic I solved it by switching to qbittiorrent-nox 
```version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            # Auth token is stored here
            - /pia-wg/pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - /pia-wg/scripts:/pia-shared
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
            - SYS_MODULE
        ports:
            - 192.168.10.190:9090:9090
            - 6881:6881/tcp
            - 6881:6881/udp
            
        environment:
            # The following env vars are required:
            - LOC=ca_vancouver
            - USER=p00000
            - PASS=pass
            # The rest are optional:
            - LOCAL_NETWORK=192.168.10.0/24
            - KEEPALIVE=25
            - VPNDNS=8.8.8.8,8.8.4.4
            - PORT_FORWARDING=1
            - WG_USERSPACE=1
            #- PORT_PERSIST=1
            - PORT_SCRIPT=/pia-shared/ports.sh 
            - FIREWALL=1
            - PORT_FILE_CLEANUP=1
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        restart: always
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

    qbittorrent-nox:
        network_mode: "service:vpn"
        container_name: qbittorrent-nox
        environment:
          #- PAGID=10000
          #- PGID=1000
          #- PUID=1000
          - QBT_EULA=accept
          - QBT_VERSION=latest
          - QBT_WEBUI_PORT=9090
          #- TZ=UTC
          #- UMASK=022
        image: qbittorrentofficial/qbittorrent-nox:latest
        read_only: true
        stop_grace_period: 30m
        tmpfs:
          - /tmp
        tty: true
        volumes:
          - /tmp:/downloads
          - /pia-wg-nox/qbt:/config
        restart: unless-stopped```

**Comment by mrchrisster** [comment]
A whole day without issues. Not sure what solved it in the end but it works well now on the newest Docker. Thanks again for your help!

**Comment by faximan** [comment]
> I was able to fix it by assigning the port to my network. `-ports: -192.168.10.190:9090:9090`

Do you understand why the IP prefix is needed here? The WebUI doesn't load for me without it, even when using qbittiorrent-nox. That's not an issue for LAN access, but it breaks down when connecting to my host remotely over my Tailscale VPN as it assigns a different IP.

**Comment by mrchrisster** [comment]
Not entirely sure tbh. I thought it was an issue specific to my network

**Comment by faximan** [comment]
> Not entirely sure tbh. I thought it was an issue specific to my network
> 
> I did not have to specify it on an older version of docker and it worked. I use vnc to connect to my server so no problem here for me

I solved it with a reverse proxy: https://github.com/thrnz/docker-wireguard-pia/issues/80#issuecomment-1572361157
